### ISSUE TITLE
No value sent in reset

### ISSUE THREAD

**Issue by Saums** [gronat/MS5611#1]
In the function reset(), the CMD_RESET register is selected but no value is written on it. Is that right? I have ported the code to Energia to run on MSP432, the code gets stuck at reset. Anyone facing similar problem?

void MS5611::reset(){
	Wire.beginTransmission(ADD_MS5611);
	Wire.write(CMD_RESET);
	Wire.endTransmission();
}

**Comment by gronat** [comment]
Wire.write(CMD_RESET) actually sends reset command (0x1E) via I2C.  You should be able to see it on the oscilloscope. The code is correct. Do you use compatible voltage levels? MSP432 is 3.3V, however, many of the MSP5611 boards available on ebay are 5V. Do you use correct pull-up resistors?

**Comment by Saums** [comment]
I tried to run it on Arduino, since it wasn't working on MSP432, I'm facing the same problem, the code gets stuck in the reset function. 

Also, I'm using the resistors.

**Comment by gronat** [comment]
Wierd, mine works fine (Arduino Nano, Arduino Micro, board form ebay) What exactly MS5611 dev board do you use? MS6511 can have two addresses on I2C, try to use both.

**Comment by Saums** [comment]
I'm using Arduino Uno. The sensor board is CJMCU-101. There MPU9150 also on the board. I checked the i2c address it is 0x77 which is same your chip.

**Comment by gronat** [comment]
Hi Samus,
It seem like you do not call barometer begin() method after creating the instance of barometer. Can you share your code? A sample code that works right now with arduino UNO and Drotek IMU+baro board is shown below:
```cpp
#include <MS5611.h>
MS5611 baro;
int32_t pressure;

void setup() {
  baro = MS5611();          // start baromater
  baro.begin();
  Serial.begin(9600);        // start serial
  delay(2);
}

void loop() {
  pressure = baro.getPressure();    // read pressure
  Serial.println(pressure);                // send via UART 
}
```
I can read the pressure in Pa units when open the Serial monitor.
